from django.db import models
from django.conf import settings
from django.utils import timezone
from Material.models import Material
from Product.models import Product
from Equipment.models import Equipment
from Documents.models import Document
from Orgnization.models import Position
from Customer.models import Customer
import bleach
from bleach.css_sanitizer import CSSSanitizer

# WYSIWYG content whitelist (HTML generated by Quill)
ALLOWED_TAGS = [
    'p', 'br', 'strong', 'b', 'em', 'i', 'u', 's', 'del', 'ol', 'ul', 'li',
    'blockquote', 'pre', 'code', 'a', 'h1', 'h2', 'h3', 'span',
]
ALLOWED_ATTRS = {'a': ['href', 'title', 'target'], 'span': ['style']}
ALLOWED_STYLES = ['color', 'background-color', 'text-align']


def clean_rich_text(value):
    """Sanitize WYSIWYG content, strip dangerous tags and attributes (drop anything outside whitelist)"""
    if not value:
        return ''
    return bleach.clean(
        value,
        tags=ALLOWED_TAGS,
        attributes=ALLOWED_ATTRS,
        css_sanitizer=CSSSanitizer(allowed_css_properties=ALLOWED_STYLES),
        strip=True,
    )


class WorkOrder(models.Model):
    """
    Work Order Model
    """
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('IN_PROGRESS', 'In Progress'),
        ('COMPLETED', 'Completed'),
        ('CANCELLED', 'Cancelled'),
        ('ABNORMAL', 'Abnormal'),
    ]
    TYPE_CHOICES = [
        ('NORMAL', 'Normal Production'),
        ('REWORK', 'Rework'),
        ('SAMPLE', 'Sample'),
        ('URGENT', 'Urgent'),
        ('OUTSOURCING', 'Outsourcing'),
        ('MAINTENANCE', 'Maintenance'),
        ('RETURN', 'Return Processing'),
    ]
    SOURCE_CHOICES = [
        ('ORDER', 'Order'),
        ('PLAN', 'Plan'),
        ('SHOPFLOOR', 'Shop Floor'),
        ('QC', 'QC'),
    ]

    order_number = models.CharField(max_length=50, unique=True, verbose_name='Work Order No.')
    customer = models.ForeignKey(
        Customer,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name='work_orders',
        verbose_name='Customer',
    )
    lot_number = models.CharField(max_length=50, blank=True, verbose_name='Lot Number')
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Product')
    quantity = models.PositiveIntegerField(verbose_name='Quantity')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING', verbose_name='Work Order Status')
    type = models.CharField(max_length=20, choices=TYPE_CHOICES, default='NORMAL', verbose_name='Work Order Type')
    source = models.CharField(max_length=20, choices=SOURCE_CHOICES, default='ORDER', verbose_name='Work Order Source')
    notes = models.TextField(blank=True, verbose_name='Remarks')
    planned_start_date = models.DateTimeField(verbose_name='Planned Start Date')
    planned_end_date = models.DateTimeField(verbose_name='Planned End Date')
    actual_start_date = models.DateTimeField(null=True, blank=True, verbose_name='Actual Start Date')
    actual_end_date = models.DateTimeField(null=True, blank=True, verbose_name='Actual End Date')

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created At')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Updated At')

    def __str__(self):
        return f"WO {self.order_number} - {self.product.name}"

    def save(self, *args, **kwargs):
        # Auto-generate lot number when empty:<Work Order No.>-01(order_number is unique, sequence always 01)
        if not self.lot_number and self.order_number:
            self.lot_number = f"{self.order_number}-01"
        super().save(*args, **kwargs)

    @property
    def current_step(self):
        """Current station: first step that is not completed or cancelled (None if all done)"""
        return self.steps.exclude(status__in=['COMPLETED', 'CANCELLED']).order_by('step_number').first()

    @property
    def previous_step(self):
        """Previous station: last completed step before current station (None if none)"""
        cur = self.current_step
        if cur is None:
            return None
        return self.steps.filter(
            step_number__lt=cur.step_number,
            status='COMPLETED',
        ).order_by('-step_number').first()

    def refresh_status_from_steps(self):
        """Auto-derive work order status from steps (cancelled steps treated as skipped, won't block flow):
        - Any abnormal → Abnormal
        - All non-cancelled steps completed → Completed (including partial cancellation)
        - All steps cancelled → Cancelled
        - Any in progress → In Progress
        - Otherwise → Pending
        """
        steps = self.steps.all()
        if not steps.exists():
            self.status = 'PENDING'
        else:
            statuses = set(steps.values_list('status', flat=True))
            active = steps.exclude(status='CANCELLED')
            if 'ABNORMAL' in statuses:
                self.status = 'ABNORMAL'
            elif not active.exists():
                self.status = 'CANCELLED'
            elif not active.exclude(status='COMPLETED').exists():
                self.status = 'COMPLETED'
            elif 'IN_PROGRESS' in statuses:
                self.status = 'IN_PROGRESS'
            else:
                self.status = 'PENDING'
        self.save(update_fields=['status'])
        return self.status

    class Meta:
        verbose_name = "Work Order"
        verbose_name_plural = "Work Orders"
        ordering = ['-created_at']


class BOM(models.Model):
    """
    Bill of Materials (BOM) header — linked to a finished Product
    """
    product = models.OneToOneField(
        Product,
        on_delete=models.PROTECT,
        related_name='bom',
        verbose_name='Finished Product',
    )
    version = models.CharField(max_length=20, default='1.0', verbose_name='Version')
    description = models.TextField(blank=True, null=True, verbose_name='Notes')
    is_active = models.BooleanField(default=True, verbose_name='Active')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created At')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Updated At')

    def __str__(self):
        return f"BOM [{self.version}] - {self.product.name}"

    class Meta:
        verbose_name = "Bill of Materials"
        verbose_name_plural = "Bill of Materials"
        ordering = ['product__name']


class BOMItem(models.Model):
    """
    BOM item — component and quantity
    """
    bom = models.ForeignKey(
        BOM,
        on_delete=models.CASCADE,
        related_name='items',
        verbose_name='Parent BOM',
    )
    component = models.ForeignKey(
        Material,
        on_delete=models.PROTECT,
        related_name='used_in_boms',
        verbose_name='Component Material',
    )
    quantity = models.DecimalField(max_digits=12, decimal_places=4, verbose_name='Quantity')
    unit = models.CharField(max_length=20, blank=True, verbose_name='UnitRemarks')
    notes = models.CharField(max_length=255, blank=True, verbose_name='Remarks')

    def __str__(self):
        return f"{self.bom} → {self.component.name} × {self.quantity}"

    class Meta:
        verbose_name = "BOM Item"
        verbose_name_plural = "BOM Item"
        unique_together = ('bom', 'component')


class ProcessStep(models.Model):
    """
    Standard Process Steps (Process Card) — linked to a Product
    Each step includes: processing instructions, personnel, equipment, materials, documents, QC requirements
    """
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='process_steps',
        verbose_name='Product',
    )
    step_number = models.PositiveIntegerField(verbose_name='Step No.')
    name = models.CharField(max_length=100, verbose_name='Step Name')
    description = models.TextField(blank=True, verbose_name='Process Guidelines')
    personnel_requirement = models.CharField(max_length=200, blank=True, verbose_name='Personnel Requirement (Text)')
    personnel = models.ForeignKey(
        Position,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='process_steps',
        verbose_name='Personnel Position',
    )
    equipment = models.ForeignKey(
        Equipment,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='process_steps',
        verbose_name='Equipment',
    )
    material = models.ForeignKey(
        Material,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='process_step_materials',
        verbose_name='Material',
    )
    document = models.ForeignKey(
        Document,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='process_steps',
        verbose_name='Reference Document',
    )
    qc_requirements = models.TextField(blank=True, verbose_name='QC Requirements')
    standard_time_minutes = models.PositiveIntegerField(null=True, blank=True, verbose_name='Std. Time (min)')

    def __str__(self):
        return f"{self.product.name} - Step {self.step_number}: {self.name}"

    def save(self, *args, **kwargs):
        self.description = clean_rich_text(self.description)
        self.qc_requirements = clean_rich_text(self.qc_requirements)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Standard Process Step"
        verbose_name_plural = "Standard Process"
        ordering = ['product', 'step_number']
        unique_together = ('product', 'step_number')


class WorkOrderStep(models.Model):
    """
    Work Order Step — auto-populated from standard process when creating work order (snapshot, adjustable)
    """
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('IN_PROGRESS', 'In Progress'),
        ('COMPLETED', 'Completed'),
        ('CANCELLED', 'Cancelled'),
        ('ABNORMAL', 'Abnormal'),
    ]

    work_order = models.ForeignKey(
        WorkOrder,
        on_delete=models.CASCADE,
        related_name='steps',
        verbose_name='Work Order',
    )
    source_step = models.ForeignKey(
        ProcessStep,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='workorder_steps',
        verbose_name='Source Process Step',
    )
    step_number = models.PositiveIntegerField(verbose_name='Step No.')
    name = models.CharField(max_length=100, verbose_name='Step Name')
    description = models.TextField(blank=True, verbose_name='Process Guidelines')
    personnel_requirement = models.CharField(max_length=200, blank=True, verbose_name='Personnel Requirement (Text)')
    personnel = models.ForeignKey(
        Position,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='workorder_steps',
        verbose_name='Personnel Position',
    )
    equipment = models.ForeignKey(
        Equipment,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='workorder_steps',
        verbose_name='Equipment',
    )
    material = models.ForeignKey(
        Material,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='workorder_step_materials',
        verbose_name='Material',
    )
    document = models.ForeignKey(
        Document,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='workorder_steps',
        verbose_name='Reference Document',
    )
    qc_requirements = models.TextField(blank=True, verbose_name='QC Requirements')
    standard_time_minutes = models.PositiveIntegerField(null=True, blank=True, verbose_name='Std. Time (min)')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING', verbose_name='Step Status')
    actual_start_date = models.DateTimeField(null=True, blank=True, verbose_name='Actual Start Time')
    actual_end_date = models.DateTimeField(null=True, blank=True, verbose_name='Actual End Time')

    received_quantity = models.PositiveIntegerField(null=True, blank=True, verbose_name='Received Quantity')
    good_quantity = models.PositiveIntegerField(null=True, blank=True, verbose_name='Good Quantity')
    defect_quantity = models.PositiveIntegerField(null=True, blank=True, verbose_name='Defect Quantity')
    loss_quantity = models.PositiveIntegerField(default=0, verbose_name='Loss Quantity')
    remarks = models.CharField(max_length=255, blank=True, verbose_name='Quantity Remarks')

    # ── Track In / Track Out ──────────────────────────────────────────
    track_in_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='tracked_in_steps',
        verbose_name='Track-In Operator',
    )
    track_out_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='tracked_out_steps',
        verbose_name='Track-Out Operator',
    )
    actual_equipment = models.ForeignKey(
        Equipment,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='actual_equipment_steps',
        verbose_name='Actual Equipment',
    )
    track_in_note = models.TextField(blank=True, verbose_name='Track In Note / Condition')
    track_out_note = models.TextField(blank=True, verbose_name='Track Out Note / Condition')
    is_picking_step = models.BooleanField(default=False, verbose_name='Is Picking Station')

    @property
    def passed_quantity(self):
        good = self.good_quantity or 0
        defect = self.defect_quantity or 0
        return good + defect

    def balance_ok(self):
        if self.received_quantity is None:
            return None  # not yet filled
        received = self.received_quantity or 0
        good = self.good_quantity or 0
        defect = self.defect_quantity or 0
        loss = self.loss_quantity or 0
        return (good + defect + loss) == received

    def __str__(self):
        return f"{self.work_order.order_number} - Step {self.step_number}: {self.name}"

    def save(self, *args, **kwargs):
        self.description = clean_rich_text(self.description)
        self.qc_requirements = clean_rich_text(self.qc_requirements)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Work Order Step"
        verbose_name_plural = "Work Order Steps"
        ordering = ['work_order', 'step_number']
        unique_together = ('work_order', 'step_number')


class MaterialPickingItem(models.Model):
    """Picking station confirmation detail: based on BOM required quantities, operator confirms actual quantity before proceeding to next step"""
    work_order = models.ForeignKey(
        WorkOrder,
        on_delete=models.CASCADE,
        related_name='picking_items',
        verbose_name='Work Order',
    )
    material = models.ForeignKey(
        Material,
        on_delete=models.PROTECT,
        verbose_name='Material',
    )
    required_quantity = models.DecimalField(max_digits=12, decimal_places=2, verbose_name='Required Quantity')
    confirmed_quantity = models.DecimalField(
        max_digits=12, decimal_places=2, null=True, blank=True, verbose_name='Confirmed Quantity'
    )
    confirmed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='confirmed_picking_items',
        verbose_name='Confirmed By',
    )
    confirmed_at = models.DateTimeField(null=True, blank=True, verbose_name='Confirmed At')
    note = models.CharField(max_length=255, blank=True, verbose_name='Remarks')

    class Meta:
        verbose_name = "Picking Confirmation Detail"
        verbose_name_plural = "Picking Confirmation Detail"
        ordering = ['material__material_id']
        unique_together = ('work_order', 'material')

    def __str__(self):
        return f"{self.work_order.order_number} - {self.material.material_id} required {self.required_quantity}"